import { Geist, Geist_Mono, Cairo, Tajawal } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// 2. إعداد الخط وتحديد الأوزان والمجموعات
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700"], // أوزان الخط من الخفيف للعريض
  variable: "--font-tajawal", // اسم المتغير الـ CSS
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${tajawal.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
